### PR TITLE
ci: Add unit and functional tests using Dart beta

### LINKED ISSUE #1785: Add at_server tests for Dart Beta releases so we can get early warning of issues caused by breaking changes
### Is your feature request related to a problem? Please describe.

Dart has a fairly aggressive minor release cadence

### Describe the solution you'd like

Run existing unit and functional tests against the Dart Beta channel

### Describe alternatives you've considered

Also run end to end tests using Beta channel dart

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cpswan**
Fixes #1785 

**- What I did**

Created new workflow to run unit tests and functional tests using Dart Beta channel

**- How I did it**

* Copied at_server workflow
* Stripped out unnecessary run conditions
* s/stable/beta/ for Dart SDK in unit tests and functional tests
* Removed all other tests

**- How to verify it**

Action will run against this PR

**- Description for the changelog**

ci: Add unit and functional tests using Dart beta

### CODE REVIEW

**Review by gkc — COMMENTED** [review]
Is there a way to reuse code from the existing workflow in the new one, rather than duplicating and editing?

**Comment by cpswan** [comment]
@gkc generally YAML isn't the best for reuse.

Having discussed with @XavierChanth I'm going to see if I can do this with a matrix; so switched to draft for now.

**Comment by xavierchanth** [comment]
This is a good example: multibuild/main_build:

https://github.com/atsign-foundation/noports/blob/trunk/.github/workflows/multibuild.yaml

**Comment by cpswan** [comment]
@gkc this now uses the same approach as https://github.com/atsign-foundation/at_client_sdk/pull/1236 and is ready to review

**Review by gkc — APPROVED** [review]

**Pull request merged**
