### PR TITLE
feat: skip commit log param in keystore

### PR DESCRIPTION
**Pull request by murali-shris**
**- What I did**
- added implementation changes for skip commit log param in keystore
**- How I did it**
- in hive_keystore.dart , if skipCommit=true for create/put/remove return -1 and don't add entry to commit log
- added unit tests in hive_keystore_impl_test.dart
**- How to verify it**
- run the test group - A group of tests to verify skip commit in hive_keystore_impl_test.dart

### CODE REVIEW

**Review by gkc — COMMENTED** [review]
LGTM

Will re-review when persistence spec has been published and dependency override has been removed

**Comment by murali-shris** [comment]
> LGTM
> 
> Will re-review when persistence spec has been published and dependency override has been removed

@gkc 
In the end2endtest staging which is failing, current version of persistence secondary in pub.dev(doesn't have optional param in impl class) and persistence spec(has the optional param in interface) are retrieved which is causing the failure. How can we resolve this failure?

**Comment by gkc** [comment]
> > LGTM
> > Will re-review when persistence spec has been published and dependency override has been removed
> 
> @gkc In the end2endtest staging which is failing, current version of persistence secondary in pub.dev(doesn't have optional param in impl class) and persistence spec(has the optional param in interface) are retrieved which is causing the failure. How can we resolve this failure?

- The problem is in the `Activating atSign` step, when doing dart pub get for the at_onboarding_cli package
- This problem will happen everywhere when anyone tries to do pub get of pretty much anything
- Quickest way forward is to approve this PR, merge it, and publish
- In order to prevent this in the future, maybe we can update the pubspec of at_persistence_secondary_server so that it depends on a specific version of at_persistence_spec
  - i.e. instead of `^2.0.12`
  - we should have `'>=2.0.11 <=2.0.12`

**Comment by gkc** [comment]
> > > LGTM
> > > Will re-review when persistence spec has been published and dependency override has been removed
> > 
> > 
> > @gkc In the end2endtest staging which is failing, current version of persistence secondary in pub.dev(doesn't have optional param in impl class) and persistence spec(has the optional param in interface) are retrieved which is causing the failure. How can we resolve this failure?
> 
> * The problem is in the `Activating atSign` step, when doing dart pub get for the at_onboarding_cli package
> * This problem will happen everywhere when anyone tries to do pub get of pretty much anything
> * Quickest way forward is to approve this PR, merge it, and publish
> * In order to prevent this in the future, maybe we can update the pubspec of at_persistence_secondary_server so that it depends on a specific version of at_persistence_spec
>   
>   * i.e. instead of `^2.0.12`
>   * we should have `'>=2.0.11 <=2.0.12`

I think we can trick the pub check with this: `  at_persistence_spec: '>2.0.12 <=2.0.13'`

**Comment by gkc** [comment]
The `end2end_test_staging` check will fail again but once we've published the new at_persistence_secondary_server and keep this pattern going forward, this problem should not recur.

**Comment by gkc** [comment]
Once we've merged to trunk and published, please do another dummy PR to
1. verify that the end2end_test_staging job will succeed
2. ensure that the jobs to build the new staging docker images run (as they are dependent on end2end_test_staging job)

**Review by gkc — APPROVED** [review]

**Comment by gkc** [comment]
Approved and merged. @murali-shris please pull from trunk and publish new version

**Comment by gkc** [comment]
@murali-shris in the interests of time, I will publish new version now, and then do the dummy PR to follow up

**Comment by gkc** [comment]
OK this is messy. I'm going to retract the new at_persistence_spec for now, because version 3.0.55 of at_persistence_secondary_server already exists (Sita published last week, but we then had to retract it because of a bug)

**Comment by gkc** [comment]
Have now published new versions of at_persistence_spec and at_persistence_secondary_server

**Pull request merged**
