### PR TITLE
config.yaml prod issue

### LINKED ISSUE #91: Error on start up of secondary without config.yaml
When starting the secondary from the command line without the config/config.yaml file in place I get the error below.. I believe the default value for **notificationQuarantineDuration** should be put in place if the config.yaml is not found like the other values.

 This could I think prevent the secondary starting up in some enviroments..

With no config.yaml in place

```secondary_1  | INFO|2021-04-16 01:29:17.087748|AtSecondaryServer|currentAtSign : @colin
secondary_1  |
secondary_1  | FINER|2021-04-16 01:29:17.092662|CommitLogKeyStore|last committed sequence: 1
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.100245|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.101842|HiveKeystore|hive key:privatekey:at_secret
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.103237|HiveKeystore|hive value:AtData{data: 1234567890qwertyuio, metaData: {createdBy: null, updatedBy: null, createdAt: 2021-04-16 01:29:17.101832Z, updatedAt: 2021-04-16 01:29:17.101832Z, availableAt: null, expiresAt: null, refreshAt: null, status: active, version: 0, ttl: null, ttb: null, ttr: null, ccd: null, isBinary: null, isEncrypted: null, dataSignature: null}
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:29:17.105754|AtRefreshJob|scheduleKeyRefreshTask runs at 6 hours
secondary_1  |
secondary_1  | Unhandled exception:
secondary_1  | NoSuchMethodError: The method '[]' was called on null.
secondary_1  | Receiver: null
secondary_1  | Tried calling: []()
secondary_1  | #0      AtSecondaryConfig.notificationQuarantineDuration (package:at_secondary/src/server/at_secondary_config.dart:544)
secondary_1  | #1      new ResourceManager._internal (package:at_secondary/src/notification/resource_manager.dart:25)
secondary_1  | #2      ResourceManager._singleton (package:at_secondary/src/notification/resource_manager.dart:13)
secondary_1  | #3      new ResourceManager.getInstance (package:at_secondary/src/notification/resource_manager.dart)
secondary_1  | #4      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:173)
secondary_1  | <asynchronous suspension>
secondary_1  | #5      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
secondary_1  | <asynchronous suspension>
secondary_1  | #6      main (file:///buddy/atsign-open-source/at_secondary/at_secondary_server/bin/main.dart:21)
secondary_1  | <asynchronous suspension>
```

But putting the file in place the secondary starts up just fine. 

```secondary_1  | INFO|2021-04-16 01:31:17.777855|AtSecondaryServer|currentAtSign : @colin
secondary_1  |
secondary_1  | FINER|2021-04-16 01:31:17.780268|CommitLogKeyStore|last committed sequence: 1
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.787286|HivePersistenceManager|scheduleKeyExpireTask starting cron job.
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.787542|HiveKeystore|hive key:privatekey:at_secret
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.787573|HiveKeystore|hive value:AtData{data: 1234567890qwertyuio, metaData: {createdBy: null, updatedBy: null, createdAt: 2021-04-16 01:31:17.787533Z, updatedAt: 2021-04-16 01:31:17.787533Z, availableAt: null, expiresAt: null, refreshAt: null, status: active, version: 0, ttl: null, ttb: null, ttr: null, ccd: null, isBinary: null, isEncrypted: null, dataSignature: null}
secondary_1  |
secondary_1  | FINEST|2021-04-16 01:31:17.788265|AtRefreshJob|scheduleKeyRefreshTask runs at 14 hours
secondary_1  |
```

### PR DESCRIPTION
**Pull request by naresh0689**

### CODE REVIEW

**Comment by cpswan** [comment]
Is this intended to fix #91 (it looks like it is, but it's always good to cross reference issues in PRs)?

I see that the code essentially checks for whether a null object gets created due to a missing config file. But if the file doesn't exist then it will still return a null object.

Looking at at_server/at_secondary/at_secondary_server/lib/src/server/at_secondary_config.dart there are plenty of sections that test for a null object e.g. at line 490:

   ```dart
   static int get rootServerPort {
     var result = _getIntEnvVar('rootServerPort');
     if (result != null) {
       return result;
     }
     if (ConfigUtil.getYaml() != null &&
         ConfigUtil.getYaml()['root_server'] != null &&
         ConfigUtil.getYaml()['root_server']['port'] != null) {
       return ConfigUtil.getYaml()['root_server']['port'];
     }
   ```
But that's not happening in the code block that threw the exception for Colin at line 544:

   ```dart
   static int get notificationQuarantineDuration {
     var result = _getIntEnvVar('notificationQuarantineDuration');
     if (result != null) {
       return _getIntEnvVar('notificationQuarantineDuration');
     }
     if (ConfigUtil.getYaml()['notification'] != null &&
         ConfigUtil.getYaml()['notification']['quarantineDuration'] != null) {
       return ConfigUtil.getYaml()['notification']['quarantineDuration'];
     }
     return _notificationQuarantineDuration;
   }
   ```

So I'm not sure this will fix the problem - I think we also need to have more thorough null checks for the config items receiving `ConfigUtil.getYaml()`

How was this change tested?

**Comment by cpswan** [comment]
Thanks @naresh0689 the refactor definitely improves the readability of the code, and improves on 'Don't Repeat Yourself' (DRY) principles.

I wonder if the following might make it even better:

1. How about a more meaningful function name than `getValue`? Something like `getConfigFromYaml`?
2. Rather than creating an `args` array on one line and then passing it on the next how about passing the `args` directly?
3. Do we need a temporary `value` to hold the function return values, or can we just test and return them directly?

e.g. Around line 531 could look like:

```dart
    if (getConfigFromYaml(['notification', 'jobFrequency']) != null) {
      return getConfigFromYaml(['notification', 'jobFrequency']);
    }
    return _notificationJobFrequency;
```

An explicit `else` might make it even more clear what's happening.

Which I think is much more obvious than the present:

```dart
    var args = ['notification', 'jobFrequency'];
    var value = getValue(args);
    if (value != null) {
      return value;
    }
    return _notificationJobFrequency;
```

Something using the ternary operator like the code we use for `version` would also be nice:

```dart
  //version
  static final String _secondaryServerVersion =
      (ConfigUtil.getPubspecConfig() != null &&
              ConfigUtil.getPubspecConfig()['version'] != null)
          ? ConfigUtil.getPubspecConfig()['version']
          : null;
```

e.g.

```dart
   return (getConfigFromYaml(['notification', 'jobFrequency']) != null)
          ? getConfigFromYaml(['notification', 'jobFrequency'])
          : _notificationJobFrequency;
```

It might be possible to make this even more elegant using a `try...catch` block where we `try` to return the Yaml elements and `catch` the element not found exception to return the `_constant`.

**Comment by cpswan** [comment]
Tests are failing:

```
lib/src/server/at_secondary_config.dart:86:10: Error: 'ElementNotFoundException' isn't a type.
    } on ElementNotFoundException {
         ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by murali-shris** [comment]
closing the PR since it is obsolete

**Comment by cpswan** [comment]
I'm not going to re-open this, but I've restored the branch because there was some good work done, which I'd still like to see find its way into trunk. (@gkc)

**Pull request closed without merging**
