### PR TITLE
fix: refactor compaction job

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
* Consume the https://github.com/atsign-foundation/at_server/pull/1113 PR changes and implement the refactor of the compaction job.
* Add generics to the AtCommitLog, AtAccessLog and AtNotificationLog classes for type safety.
* Remove the time-based compaction and size-based compaction files because that are not in use.
* Add unit tests for the compaction.
* Updated at_commons and at_persistence_spec versions in pubspec.yaml

**- How to verify it**
* Unit tests to verify the changes to commit log compaction
* The tests in the at_secondary_server should pass to ensure that there are no breaking changes.

**- Description for the changelog**
* fix: Refactor commit log compaction to enable compaction on the client side.

### CODE REVIEW

**Comment by murali-shris** [comment]
@kalluriramkumar changes have to be tested by using the persistence changes on at client and then this PR needs to be merged.

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar changes have to be tested by using the persistence changes on at client and then this PR needs to be merged.

Yes, @murali-shris. I have manually tested the changes with the at_client package and on the client side, the commit log is getting compacted as excepted. At the moment, the PR in at_client is failing because of converting the key to lowercase.

**Comment by gkc** [comment]
Is this still a draft or is it ready for review?

**Comment by sitaram-kalluri** [comment]
> Is this still a draft or is it ready for review?

This is ready for review. Marked as draft because the dependency overrides needs to be updated with the hosted version.

**Review by gkc — DISMISSED** [review]

**Review by murali-shris — APPROVED** [review]

**Pull request merged**
