### PR TITLE
feat: added notification type for apkam enrollments

### PR DESCRIPTION
**Pull request by murali-shris**
**- What I did**
- added self notification type for apkam enrollments
**- How I did it**
- introduced "self" value in NotificationType enum
- in at_notification_callback.dart added logic to invoke callbacks when notification type is NotificationType.self
- added unit test at_notification_callback_test.dart
- upgraded at_commons and at_utils version in pubspec
**- How to verify it**
- run the unit test at_notification_callback_test.dart

### CODE REVIEW

**Comment by gkc** [comment]
@murali-shris how does AtClient handle these new 'self' notifications?

**Review by sitaram-kalluri — DISMISSED** [review]

**Comment by murali-shris** [comment]
> @murali-shris how does AtClient handle these new 'self' notifications?

Currently self notifications are not written to monitor from server.hence they will not be received on at_client monitor. 
In apps that can approve/deny enrollments we have to subscribe to regex matching the namespace '__manage'

**Comment by gkc** [comment]
> > @murali-shris how does AtClient handle these new 'self' notifications?
> 
> Currently self notifications are not written to monitor from server.hence they will not be received on at_client monitor. In apps that can approve/deny enrollments we have to subscribe to regex matching the namespace '__manage'

We need to guard in some way against an old client version receiving a self notification which it won't be able to understand because it's an old client version. I'd suggest adding a flag to the monitor verb syntax and adjusting the verb handler behaviour accordingly

**Review by gkc — CHANGES_REQUESTED** [review]
We need to guard in some way against an old client version receiving a self notification which it won't be able to understand because it's an old client version. I'd suggest adding a flag to the monitor verb syntax and adjusting the verb handler behaviour accordingly

**Comment by murali-shris** [comment]
> We need to guard in some way against an old client version receiving a self notification which it won't be able to understand because it's an old client version. I'd suggest adding a flag to the monitor verb syntax and adjusting the verb handler behaviour accordingly

I implemented the check without changing monitor syntax. Please check whether the approach is fine

https://github.com/atsign-foundation/at_client_sdk/commit/a4e0e1b320c9de9c7ad4391955aa13a7c6e69322
https://github.com/atsign-foundation/at_server/commit/6db29c4bfe98a853cae2ef2ab86fd3756e309ed9

**Comment by murali-shris** [comment]
> > We need to guard in some way against an old client version receiving a self notification which it won't be able to understand because it's an old client version. I'd suggest adding a flag to the monitor verb syntax and adjusting the verb handler behaviour accordingly
> 
> I implemented the check without changing monitor syntax. Please check whether the approach is fine
> 
> [atsign-foundation/at_client_sdk@a4e0e1b](https://github.com/atsign-foundation/at_client_sdk/commit/a4e0e1b320c9de9c7ad4391955aa13a7c6e69322) [6db29c4](https://github.com/atsign-foundation/at_server/commit/6db29c4bfe98a853cae2ef2ab86fd3756e309ed9)

reverted the version compare changes and replaced with self notification flag in monitor verb
https://github.com/atsign-foundation/at_libraries/pull/375
https://github.com/atsign-foundation/at_server/commit/7b8ff048c4cf0918e35c34062893733073df5e5c

**Comment by gkc** [comment]
> > > We need to guard in some way against an old client version receiving a self notification which it won't be able to understand because it's an old client version. I'd suggest adding a flag to the monitor verb syntax and adjusting the verb handler behaviour accordingly
> > 
> > 
> > I implemented the check without changing monitor syntax. Please check whether the approach is fine
> > [atsign-foundation/at_client_sdk@a4e0e1b](https://github.com/atsign-foundation/at_client_sdk/commit/a4e0e1b320c9de9c7ad4391955aa13a7c6e69322) [6db29c4](https://github.com/atsign-foundation/at_server/commit/6db29c4bfe98a853cae2ef2ab86fd3756e309ed9)
> 
> reverted the version compare changes and replaced with self notification flag in monitor verb [atsign-foundation/at_libraries#375](https://github.com/atsign-foundation/at_libraries/pull/375) [7b8ff04](https://github.com/atsign-foundation/at_server/commit/7b8ff048c4cf0918e35c34062893733073df5e5c)

Reviewed and approved at_libraries#375

**Comment by murali-shris** [comment]
@gkc I have to merge this PR, publish at_persistence_secondary and then make the merge the changes in monitor verb handler on server.

**Review by gkc — APPROVED** [review]

**Pull request merged**
