### PR TITLE
build: bump dart to 3.1.5

### PR DESCRIPTION
**Pull request by gkc**
Rollup of #1642 #1643 #1644 #1645

### CODE REVIEW

**Comment by gkc** [comment]
Two of the functional tests are failing repeatedly - @sitaram-kalluri is investigating

**Comment by gkc** [comment]
Merge run of #1622 also failed in the same way https://github.com/atsign-foundation/at_server/actions/runs/6650002663

**Review by cpswan — APPROVED** [review]

**Comment by cpswan** [comment]
LGTM @gkc but obviously we need those tests to be passing before we merge

Did you use the rollup.sh script, or do the branch merges by hand?

**Comment by gkc** [comment]
I rolled up by hand. Re the test failures - for sure. Weird thing is that the same two functional tests failed in the merge run for #1622 but passed in the checks on #1622 prior to merge. Anyhow - @sitaram-kalluri is on the case

**Pull request merged**
