### PR TITLE
shared key and public key checksum support for notify

### PR DESCRIPTION
**Pull request by murali-shris**
**- What I did**
- added shared key and public key checksum support in notify
**- How I did it**
- modified notify verb handler to set the metadata when sharedkey and publickey checksum are passed in notify verb
**- How to verify it**
- run the unit test in notify_verb_test.dart "A group of tests to verify public key checksum and shared key on metadata "
**- Description for the changelog**
- Notify verb handler changes for shared key and public key checksum in metadata

### CODE REVIEW

**Review by gkc — COMMENTED** [review]
LGTM - only one question - are there functional or e2e tests for this? If not, we should add them.

(If there already are functional/e2e tests in the at_client_sdk repo for example, then that's fine of course)

**Comment by murali-shris** [comment]
> LGTM - only one question - are there functional or e2e tests for this? If not, we should add them.
> 
> (If there already are functional/e2e tests in the at_client_sdk repo for example, then that's fine of course)

For the at_client PR..I have added an end2end test. I will add a test in server as well..

**Review by sitaram-kalluri — APPROVED** [review]

**Comment by murali-shris** [comment]
> > LGTM - only one question - are there functional or e2e tests for this? If not, we should add them.
> > (If there already are functional/e2e tests in the at_client_sdk repo for example, then that's fine of course)
> 
> For the at_client PR..I have added an end2end test. I will add a test in server as well..

@gkc The test I added is failing because server in prod/trunk will be on old version(which doesn't understand new notify syntax).

**Comment by gkc** [comment]
Ah! Ok, cool. We can add the test later, when this is in prod.

**Pull request merged**
