### PR TITLE
Fixes for issue #501

### PR DESCRIPTION
**Pull request by gkc**
Changes to address https://github.com/atsign-foundation/at_server/issues/501#issuecomment-1030029839

* outbound_message_listener.dart - old version would not handle error: responses but timeout after 5 seconds returning empty string
  * Modified read() so
    * it handles `error:...` responses by throwing an AtConnectException but leaves the connection open, as 'error:' is a valid response
    * handles malformed responses by throwing an AtConnectException and **closing** the connection (malformed responses should never occur)
    * changed default timeout from 5 seconds to 3 seconds as per comment from @cconstab 
    * throws a TimeoutException upon timing out, and closes the connection as timeouts are generally bad news
  * Modified _closeClient() so it doesn't check `if (!outboundClient.isInValid())` before calling outboundClient.close() - why? See [comments in code](https://github.com/atsign-foundation/at_server/pull/504/files#diff-1256148a521ddac147864fcc4cfd28c50b9974dfcbde0aa3531d60637233acf2R108)
  * Tidied up method comments for accuracy
  * For readability purposes, renamed instance variable client to outboundClient, and renamed method _closeClient to _closeOutboundClient

* outbound_connection_impl.dart
  * call socket.destroy() instead of socket.close()
  * We already call socket.destroy() in the at_lookup library see https://github.com/atsign-foundation/at_libraries/blob/trunk/at_lookup/lib/src/connection/base_connection.dart#L24 so this is normal behaviour when connecting to secondary servers
    * Originally changed base_connection.dart as well but reverted that just to prevent any unexpected side effects on **inbound_connection_impl** from this PR

* global_exception_handler.dart
  * added handling for AtConnectException and TimeoutException which are now being thrown by outbound_message_listener.dart

* proxy_lookup_verb_handler.dart
  * Added only an explanatory comment, about timeouts, 'error:..' responses and malformed responses being handled downstream in outbound_message_listener.dart

* Modified outbound_client.dart so that outbound_message_listener.dart log messages can include the remote atSign, host and port

**- Description for the changelog**
Changes to address https://github.com/atsign-foundation/at_server/issues/501#issuecomment-1030029839

### CODE REVIEW

**Comment by gkc** [comment]
Something weird is happening with e2e tests not being able to open sockets. Debugging.

**Comment by gkc** [comment]
pubspec.yaml currently has dependency override to pick up at_commons from trunk; this is because of the new exception that has been added, TimeoutException

Plan is to publish another version of at_commons and then remove the dependency override from here

**Comment by gkc** [comment]
Need to add e2e test to verify expected behaviour

**Review by sitaram-kalluri — APPROVED** [review]

**Review by cconstab — APPROVED** [review]
My only comment is that 5 seconds is an eternity to wait for a response.. Esp if you have multiple timeouts.. Perhaps needs some testing but my gut says 1 second is plenty and if the secondary has not responded in a second then it is pretty unwell..
A conservative figure I thought I used 2 years back was 3 seconds, so not sure where 5 came from..


  Future<String?> read({int maxWaitMilliSeconds = 5000}) async {

**Comment by gkc** [comment]
Agreed. All of the timeouts need to be reviewed but in the meanwhile I’ll
set this to 2 seconds

**Review by VJag — APPROVED** [review]

**Pull request merged**
