### PR TITLE
fix: Refactor commit log keystore and unit tests

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
- Refactor the AtCommitLog to segregate the methods used by the client and the server by preserving the backward compatibility.
- Refactor and update the unit tests in commit_log_test.dart
- Upgraded the at_commons package and in the sync_unit_test.dart, replace the deprecated variables with new variables. 

**- How I did it**
- Changes in CommitLogKeyStore.dart
  - Previously, the `CommitLogKeyStore` implements `HiveBase`.  As a part of refactoring, introduced a class `BaseCommitLogKeyStore` which implements `HiveBase` and `CommitLogKeyStore` extends `BaseCommitLogKeystore`
  - The methods that are common between the server and the client are placed in BaseCommitLogKeyStore.
  - The "CommitLogKeyStore" has all the methods which are specific to the server.
  - Introduced a new class `ClientCommitLogKeyStore` which has methods specific to the at_client
  - Replaced `commitLogCacheMap` with a new class `CommitLogCache` which to maintain cache of a key and its latest commit entry

- Changes in AtCommitLog 
  - Previously, the "AtCommitLog" implements AtLogType. As a part of refactoring, introduced a class `BaseAtCommitLog` which implements `AtLogType` which is a base class. The AtCommitLog extends BaseAtCommitLog which contains methods specific to server. 
  - Introduced a new `ClientAtCommitLog` which extends AtCommitLog which contains methods specific to client.

- Changes in commit_log_test.dart
  - Classified all the tests into two group
   - "A group of tests on client commit log" which assert the commit log changes for the client.
   - "A group of tests on server commit log" which assert the commit log changes for the server.
   - "A group of tests to verify commit log instances" which asserts on if the correct instance of `CommitLogKeyStore` is returned basing on the "enableCommitId" parameter.
   - Move "getChanges" from AtCommitLog to ClientAtCommitLog and update the unit tests accordingly.

**- How to verify it**
- All the test unit tests in at_persistence_secondary_server should pass.
- All the unit and functional tests in at_secondary_server should pass. Ran tests in local and tests are successful. Will raise a draft PR with at_secondary_server pointing to this persistence.
- All the unit and functional tests in at_client should pass. Ran tests in local and tests are successful. Will raise a draft PR with at_client pointing to this persistence.

**- Description for the changelog**

### CODE REVIEW

**Review by gkc — COMMENTED** [review]
LGTM. This will need extensive manual testing in addition to the existing automated tests, and please think also if there are any additional tests that should be added to the unit test pack here

**Comment by sitaram-kalluri** [comment]
> LGTM. This will need extensive manual testing in addition to the existing automated tests, and please think also if there are any additional tests that should be added to the unit test pack here

Sure Gary. Will do a round of manual testing, primarily focusing on sync between the client and the server and vice versa and other scenarios too.

**Comment by purnimavenkatasubbu** [comment]
Tested the following scenarios

- Multiple updates of a key
- Multiple deletes of a key
- Multiple deletes and the last operation is an update
- lastSyncedEntryWIth regex
- server ahead and client ahead

Did a round of sanity testing of the apps with this server branch.

**Comment by gkc** [comment]
@sitaram-kalluri Please can you link the PRs you raised in other repos which were using this branch?

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri Please can you link the PRs you raised in other repos which were using this branch?

As of now, we do not have changes in other repos.

**Comment by gkc** [comment]
> > @sitaram-kalluri Please can you link the PRs you raised in other repos which were using this branch?
> 
> As of now, we do not have changes in other repos.

You mentioned in the PR description above
> Will raise a draft PR with at_secondary_server pointing to this persistence.

and 
> Will raise a draft PR with at_client pointing to this persistence.

**Comment by sitaram-kalluri** [comment]
> > > @sitaram-kalluri Please can you link the PRs you raised in other repos which were using this branch?
> > 
> > As of now, we do not have changes in other repos.
> 
> You mentioned in the PR description above
> > Will raise a draft PR with at_secondary_server pointing to this persistence.
> 
> and 
> > Will raise a draft PR with at_client pointing to this persistence.

Sorry, i mistook the question for any related changes. I will raise the draft PR's and link them here.

**Comment by gkc** [comment]
> > > > @sitaram-kalluri Please can you link the PRs you raised in other repos which were using this branch?
> > > 
> > > 
> > > As of now, we do not have changes in other repos.
> > 
> > 
> > You mentioned in the PR description above
> > > Will raise a draft PR with at_secondary_server pointing to this persistence.
> > 
> > 
> > and
> > > Will raise a draft PR with at_client pointing to this persistence.
> 
> Sorry, i mistook the question for any related changes. I will raise the draft PR's and link them here.

I don't see the links to the draft PRs?

**Comment by sitaram-kalluri** [comment]
> > > > @sitaram-kalluri Please can you link the PRs you raised in other repos which were using this branch?
> > > 
> > > 
> > > As of now, we do not have changes in other repos.
> > 
> > 
> > You mentioned in the PR description above
> > > Will raise a draft PR with at_secondary_server pointing to this persistence.
> > 
> > 
> > and
> > > Will raise a draft PR with at_client pointing to this persistence.
> 
> Sorry, i mistook the question for any related changes. I will raise the draft PR's and link them here.

at_server: https://github.com/atsign-foundation/at_server/pull/1566
at_client: https://github.com/atsign-foundation/at_client_sdk/pull/1132

**Comment by sitaram-kalluri** [comment]
> > > > > @sitaram-kalluri Please can you link the PRs you raised in other repos which were using this branch?
> > > > 
> > > > 
> > > > As of now, we do not have changes in other repos.
> > > 
> > > 
> > > You mentioned in the PR description above
> > > > Will raise a draft PR with at_secondary_server pointing to this persistence.
> > > 
> > > 
> > > and
> > > > Will raise a draft PR with at_client pointing to this persistence.
> > 
> > 
> > Sorry, i mistook the question for any related changes. I will raise the draft PR's and link them here.
> 
> I don't see the links to the draft PRs?

**Review by gkc — APPROVED** [review]

**Pull request merged**
