### PR TITLE
Fold at_virtual_environment into at_server

### PR DESCRIPTION
**Pull request by cpswan**
ToDo:

- [x] Migrate certificate automation
- [x] Release of VE to Docker Hub

Fixes https://github.com/atsign-foundation/at_virtual_environment/issues/27

**- What I did**

New Dockerfile based on Debian with massively reduced number of steps and cleaner copying of files from repo to image.

Removed Virtual Environment stuff from at_functional_tests

Modified at_server automation workflow to use it

**- How to verify it**

This PR will run automated tests.

**- Description for the changelog**

Fold at_virtual_environment into at_server

### CODE REVIEW

**Review by cconstab — APPROVED** [review]
So much neater !

One small improvement would be to use

`sleep infinity`

in import.sh

the sleep is important but infinity works nicely 

Thanks Chris

**Comment by cpswan** [comment]
@gkc I've put the end to end test concurrency groups into this PR since I was working on that workflow definition anyway.

**Comment by gkc** [comment]
V v cool, thanks Chris

**Comment by cpswan** [comment]
@gkc @cconstab @purnimavenkatasubbu as we (re)build virtual environment A LOT for functional tests I've split it in two:
1. ve_base - which does all the apt-get stuff for dependencies, and carries all the bits that never or rarely change (like root and install_PKAM_keys)
2. ve - which copies the secondary binary on top of ve_base to complete the stack
This makes building ve take seconds, and ve_base will be rebuilt (at least) weekly to ensure dependencies are kept updated.

**Comment by gkc** [comment]
Fantastic! Thanks Chris!

**Comment by cpswan** [comment]
@kalluriramkumar this is ready to merge, and I'd like your review before I do that as there are a bunch of changes in the GitHub Actions etc.

**Review by sitaram-kalluri — APPROVED** [review]

**Pull request merged**
